# Site settings
title: Deconstructed ▧ Reconstructed
subtitle: Cédric Bastin
description: >
  personal blog - archive for written thoughts.
baseurl: ""
url: "https://cedricbastin.github.io"
github_username: cedricbastin
twitter_username: cedricbastin
linkedin_username: cedricbastin

# Build settings
markdown: kramdown

# Disqus
disqus:
  shortname: https-cedricbastin-github-io
