# Site settings
title: Deconstructed Reconstructed
subtitle: Cédric Bastin
description: >
  My personal blog / a safe archive for written words.
baseurl: ""
url: "https://cedricbastin.github.io"
github_username: cedricbastin
twitter_username: cedricbastin
linkedin_username: cedricbastin

# Build settings
markdown: kramdown
